### ISSUE TITLE
Should we add LearnIT Girl to the list?

### ISSUE THREAD

**Issue by sara-02** [tapasweni-pathak/SOC-Programs#22]
Learn IT Girl: https://www.learnitgirl.com/

**Comment by djokester** [comment]
No. This is not a Summer/Season of Code program. The aim of SOCs are not to help people learn programming. SoC programs typically encourage and help increase open source participation and help students get project experience through a few months of open source programming.

**Comment by sara-02** [comment]
@djokester Thanks for clarifying the point.
