### ISSUE TITLE
Add Concept to Clinic

### ISSUE THREAD

**Issue by palash25** [tapasweni-pathak/SOC-Programs#48]
It is an ongoing open source competition https://concepttoclinic.drivendata.org/
 
claiming this

**Comment by palash25** [comment]
On second thoughts this contest will end this year in Feb but this organization organizes open source competitions regularly. Should I just include the competitions page link of this website? ping @tapasweni-pathak

**Comment by tapasweni-pathak** [comment]
> It is an ongoing open source competition https://concepttoclinic.drivendata.org/

It would be useful to add it here http://opensourcehelpcommunity.herokuapp.com/.

> On second thoughts this contest will end this year in Feb but this organization organizes open source competitions regularly. Should I just include the competitions page link https://www.drivendata.org/competitions/ of this website? ping @tapasweni-pathak

If they are all open source competitions, please go ahead. 🎉
