### ISSUE TITLE
Add Quantopian Open

### ISSUE THREAD

**Issue by palash25** [tapasweni-pathak/SOC-Programs#49]
Organizes competitions every month where top 3 are awarded cash prizes.
https://www.quantopian.com/open

**Comment by palash25** [comment]
claiming this

**Comment by tapasweni-pathak** [comment]
Good to add it here http://opensourcehelpcommunity.herokuapp.com/contests/.

**Comment by palash25** [comment]
I have added it here http://opensourcehelpcommunity.herokuapp.com/contests/
Should I also add it to this repo?
