### ISSUE TITLE
Add OSS World Challenge

### ISSUE THREAD

**Issue by palash25** [tapasweni-pathak/SOC-Programs#50]
http://ossaward.org/eng/m0101.do
Held in Korea annually.
Sadly they closed international applications in 2017 but they might bring it back.

**Comment by tapasweni-pathak** [comment]
If it has happened even after a break of one year, would be great to have in the list, also if it is a open source competition feel free to submit it here http://opensourcehelpcommunity.herokuapp.com/contests/.
